name: Endless Mutation
favicon: null
layout_spectrum: 0.87689
typography_spectrum: 0.26439
title: Endless Mutation Center for Strange Youth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d6b101'
    - '#302c21'
    - '#e74f38'
    - '#00692e'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
